name: Auto Merge
on:
    workflow_run:
        workflows:
            - Terraform
        types:
            - completed
jobs:
    auto-merge:
        name: Merge
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
            contents: write
        steps:
            - uses: fastify/github-action-merge-dependabot@v3.0.0
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
